#!/usr/bin/env python3

import os
import sys

helpMsg = """
mkgif: convert some input into a gif using ffmpeg.

usage: mkgif input.mkv output.gif [optional: scale number, default 1000]

examples:
  mkgif input.mkv # outputs input.gif
  mkgif input.mkv output.gif
  mkgif input.mkv output.gif 500
""".strip()

if len(sys.argv) == 1:
    print(helpMsg)

elif len(sys.argv) < 2:
    print("you must provide at least one arg for input.")
    print(helpMsg)
    exit(1)

else:
    inPath = sys.argv[1]
    outPath = sys.argv[2] if len(sys.argv) > 2 else os.path.basename(inPath) + ".gif"
    scale = sys.argv[3] if len(sys.argv) > 3 else -1000

    palette = "/tmp/palette.png"
    filters=f"fps=15,scale={scale}:-1:flags=lanczos"

    os.system(f"ffmpeg -v warning -i \"{inPath}\" -vf \"{filters},palettegen\" -y {palette}")
    os.system(f"ffmpeg -v warning -i \"{inPath}\" -i {palette} -lavfi \"{filters} [x]; [x][1:v] paletteuse\" -y \"{outPath}\"")

    print("ran ffmpeg successfully.")
