name: My Workflow
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: nix
        run: |
          curl https://nixos.org/nix/install | sh
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          nix-build
      - name: run mkgif
        run: |
          ./result/bin/mkgif
          file test/touroku.m4v
          file test/touroku.gif
          ./result/bin/mkgif test/touroku.m4v test/touroku.gif 200