name: My Workflow
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: nix
        run: |
          curl https://nixos.org/nix/install | sh
      - name: run tests
        run: |
          . /home/runner/.nix-profile/etc/profile.d/nix.sh
          ./test/tests.bash
